#!/bin/sh
echo "Please enter a choice:\c"
read var

num=0
for((i=1;i<=100;i++))
    do
        num=$(($num+$i))
    done
echo "this sum of 1+2+...+100 is: $num"


case $var in
    yes | y | Y) echo "true";;
    no | N |n) echo "No";;
    *) echo "input error!"

esac

exit 0
