#!/bin/sh
read -p  "Please enter a choice:" var

num=0
for(( i=1;i<=100;i++ ))
    do
        num=$(($num+$i))
    done
echo "this sum of 1+2+...+100 is: $num"


case $var in
    yes | y | Y) echo "true";;
    no | N |n) echo "No";;
    *) echo "input error!"

esac

exit 0
