#!/bin/bash
# 变量赋值时，等号两面不能有空格
data="first shell scrip"
val = dasd
# 只读模式:
readonly img="this is img"

echo "执行条件语句"
read -p "Enter a num:" num

# 条件语句
if [ $num -ge 60 ]
	then
		echo "及格"
elif [ $num -le 50 ]
	then
		echo "不及格"
else
	echo "优秀"
fi 

# 循环语句
echo "执行循环"
for i in a b c d e
	do
		echo "Var is :$i"
	done

s=1
i=10
while [ $i -le 100 ]
	do
		s=$(($s+$i))
		i=$(($i+2))
	done 
echo $s
# 一般语句
echo "执行变量输出"
echo 'data is:'
echo $data
echo "$data"
echo '$data'

echo "结束编程"

exit 0
